### ISSUE TITLE
Replace loop statements in reqs with finite for loops

### ISSUE THREAD

**Issue by grumbach** [maidsafe/safe_network#2192]
See discussion below

__Originally posted by @grumbach in https://github.com/maidsafe/safe_network/pull/2189#discussion_r1135187842__

**Comment by joaoag** [comment]
Hello @grumbach 👋🏻 
I was following the loop discussion on https://github.com/maidsafe/temp_safe_network/pull/2189 and saw this issue, but I haven't been able to see where it the issue was resolved. Could you point me to it?
Apologies if this is a silly question, I want to contribute to the repo but I'm still in the process of wrapping my head around the code.
Thanks!
